### ISSUE TITLE
Ability to purge cache for a URL

### ISSUE THREAD

**Issue by jacobloveless** [edgemesh/server#1]
**Is your feature request related to a problem? Please describe:**
In an instance where a particular page is pushed live, but has a bad piece of code  - we may need to purge just that page (and not wait the 15m maximum period).

**Describe the solution you'd like:**
Add Purge URL to API endpoint

**Describe alternatives you've considered:**
Wiating up to 15m with a busted page.

**Additional context:**
I think this can be exposed as a proxied Endpoint to the purge by URL (which worked in this case we had today)

**Comment by SupremeTechnopriest** [comment]
You want a CLI command to purge a specific url instead of the whole host?

**Comment by jacobloveless** [comment]
Eventually a customer facing api.
I can use the cf interface today (which is what I used this evening).
But cli FTW as well👍

**Comment by SupremeTechnopriest** [comment]
We should work the customer facing api into the development schedule along with a portal sprint.  Prioritize it against new features.  I can def add it to the CLI on Monday.

**Comment by jacobloveless** [comment]
👍

**Comment by SupremeTechnopriest** [comment]
The core of this is done.  Just needs to be added to the CLI and portal.  In the mean time it can be cleared via the cloudflare portal via Cache Tag.
