### ISSUE TITLE
Add `preview_theme_id` and `localhost` to exceptions to the redirect

### ISSUE THREAD

**Issue by jacobloveless** [edgemesh/server#11]
Customers can use a `preview_theme_id` on Shopify to change the layout - this would automatically bypass Edgemesh the first time as its a new parameter not on the skip list - but we should add this to our preview exceptions in the redirect script for Shopify.

Also an example:
> We use browsersync to create a proxy of bokksu.com with the preview theme id. Now, when we go to localhost:3000 proxy, it kicks us through checkouts.bokksu.com then bokksu.com.
 
![image](https://user-images.githubusercontent.com/20774514/136234991-5cf1859a-b4ae-451c-803f-0fdd151c2294.png)

**Comment by SupremeTechnopriest** [comment]
Added.  Will be released in `1.4.1`.  I also added `127.0.0.1` for localhost as well.
