### ISSUE TITLE
Add Capability to not index backend origins

### ISSUE THREAD

**Issue by jacobloveless** [edgemesh/server#12]
Although the JavaScript redirect is followed by crawlers, and more specifically www and non-www domains are collapsed in the index (similar to how they are done in the browser) ... there are still some scenarios in which a backend source page would need to ensure it is not indexed or crawled.

The cleanest way to do this is to have customers add the following meta tag in their HTML

```html
<meta name="robots" content="noindex, nofollow">
```

This tag ensures that (similar to robots.txt) this page cannot be indexed.
However since we want to ensure these pages _are_ indexed on the frontend, EMS would need a method to strip this specific tag.

More generally, there might be a solution where customers can add HTML attributes on their source pages - but inform EMS that these attributes should be removed for the frontend.

**Comment by SupremeTechnopriest** [comment]
Added a new element directive `data-em-modify`.  You can set this directive to `remove` and Edgemesh Server will remove the element for pages that it serves.  In this case adding the following to `theme.liquid` will make robots skip indexing the Shopify "backend" site and only index the Edgemesh optimized site.

```html
<meta name="robots" content="noindex, nofollow" data-em-modify="remove">
```

This will be released at the end of the day today.
