### ISSUE TITLE
Edgemesh Client injection invalidates an AMP enabled page

### ISSUE THREAD

**Issue by jacobloveless** [edgemesh/server#4]
Because we inject the JavaScript client at the edge -  if the page is an AMP page we can trigger an invalidation.
We can see this via the AMP validator:
https://search.google.com/test/amp?id=gHovZPvEacdZLqEHJiHeVg

![image](https://user-images.githubusercontent.com/20774514/132554283-343222d9-828a-4856-aaa7-f8e79dd45eb4.png)

I think the best (?) path here is to not inject the client script if the document is AMP HTML which can be detected via the first line of the HTML (if it has `<html amp` like:
```html
<html amp="" lang="en">
```

**Comment by SupremeTechnopriest** [comment]
This is resolved and deployed as version `1.3.1`.
