### ISSUE TITLE
Shopify HMAC protected fonts can 401

### ISSUE THREAD

**Issue by jacobloveless** [edgemesh/server#6]
For EMS sites, we can get a 401 response for fonts protected by HMAC controls (e.g. https://fonts.shopifycdn.com).
If we em-bypass a page we do not see the 401 response.

Some examples:
Chrome w/ em-bypass (no 401)
https://webpagetest.org/result/210909_AiDc23_0d78c1f1635b34a104199fc65bfbb0a8/1/details/#waterfall_view_step1

Chrome w/o em-bypass (returns 401)
https://webpagetest.org/result/210909_AiDcRB_648754882fda06932d10cb4c5b5208c5/1/details/#waterfall_view_step1

**Comment by SupremeTechnopriest** [comment]
This is resolved in `1.3.2`
