### ISSUE TITLE
[Shopify] /discounts path needs cookie Set

### ISSUE THREAD

**Issue by jacobloveless** [edgemesh/server#7]
On Shopify based stores, customers can generate a discount code URL (see: https://help.shopify.com/en/manual/discounts/managing-discount-codes)

The URL structure is (often with the redirect parameter)
`https://<your shop url>/discount/<your discount code>?redirect=/products/<your product>`

What happens is, a cookie is set by the server (the cookie is `discount_code`) such that when a user gets to the checkout page, the cookie is read (so it must be on the checkout domain) andis automatically entered into the discount code field.

The likely best path is to treat the `/discounts/` subroute similar to how we treat other server-side dependant routes.
There are two entry paths:

**1. A link generated pointing to the checkout URL such as**
`https://<checkout-url>/discount/<your discount code>?redirect=/products/<your product>`
Here we simply need to ensure that the redirect code built into EMS does not trigger, such that the cookie can be set.
E.g. this works as intended if the following URL were used:
`https://<your shop url>/discount/<your discount code>?redirect=/products/<your product>&no-redirect=true`
What happens in the above case is the cookie is set, and the Shopify `redirect` parameter bounces the user to the relative path (still on the checkout domain) which _then_ 302's back to the main site. 

**2. A link generated pointing to the EMS URL such as**
`https://<ems-url>/discount/<your discount code>?redirect=/products/<your product>`
Here we need to respond with the 302 to the link in #1 above (`https://<checkout-url>/discount/<your discount code>?redirect=/products/<your product>`) and simply allow the fall-through of that code.

**Comment by SupremeTechnopriest** [comment]
This issue is resolved and will be deployed in version `1.3.4`
